services:
  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - task_manager

volumes:
  db_data:

networks:
  task_manager:
